LaravelProject/routes/web.php
<?php
setTImezone();
Route::get('/', function() {
    return redirect(route('admin.dashboard'));           
});


Route::get('home', function() {

    /*pre(Session::all());
    die();*/
    
    if (Session::get('role_id') == '2'){
      return redirect(route('admin.userdashboard'));  
    }
    if (Session::get('role_id') == '3'){
      return redirect(route('admin.supportdashboard'));
    }else{
        return redirect(route('admin.dashboard'));
    }
    
});



Route::group(['middleware' => ['isadmin','isactive']], function () {
    Route::name('admin.')->prefix('admin')->middleware('auth')->group(function() {

        Route::group(['middleware' => 'islavel1'], function () {
            include_route_files(__DIR__.'/Admin/');
        });

        Route::group(['middleware' => 'islavel2'], function () {
            include_route_files(__DIR__.'/Adminuser/');
        });

        Route::group(['middleware' => 'islavel3'], function () {
            include_route_files(__DIR__.'/Adminsupport/');
        });
        
    });
});



Route::group(['middleware' => 'isfirm'], function () {

    Route::name('firm.')->prefix('firm')->middleware('auth')->group(function() {
        
        Route::group(['middleware' => 'islavel1'], function () {
            
            Route::get('first_reset_admin_password', 'firmadmin\FirmDashboardController@first_reset_password')->name('first_reset_admin_password');

            Route::post('update_first_admin_password', 'firmadmin\FirmDashboardController@update_first_password')->name('update_first_admin_password');

            Route::group(['middleware' => 'resetpassword'], function () {

                Route::get('admindashboard', 'firmadmin\FirmDashboardController@index')->name('admindashboard');
                Route::get('payment_method1', 'firmadmin\FirmDashboardController@payment_method1')->name('firm.payment_method1');
                Route::get('create_charge1', 'firmadmin\FirmDashboardController@create_charge1')->name('firm.create_charge1');
                
                Route::get('caseIsConform/{id}', 'firmadmin\FirmDashboardController@caseIsConform')->name('firm.caseIsConform');
                
                Route::group(['middleware' => 'isactive'], function () {
                    include_route_files(__DIR__.'/Firmadmin/');
                });
            });

        });

        Route::group(['middleware' => ['islavel2','isactive']], function () {

            Route::get('first_reset_user_password', 'firmuser\FirmuserDashboardController@first_reset_password')->name('first_reset_user_password');

            Route::post('update_first_user_password', 'firmuser\FirmuserDashboardController@update_first_password')->name('update_first_user_password');

            Route::group(['middleware' => 'resetpassword'], function () {

                include_route_files(__DIR__.'/Firmuser/'); 

            });
        });

        Route::group(['middleware' => ['islavel3','isactive']], function () {

            Route::get('first_reset_client_password', 'firmclient\FirmclientDashboardController@first_reset_password')->name('first_reset_client_password');

            Route::post('update_first_client_password', 'firmclient\FirmclientDashboardController@update_first_password')->name('update_first_client_password');

            Route::group(['middleware' => 'resetpassword'], function () {
                include_route_files(__DIR__.'/Firmclient/');
            });
        });
        Route::group(['middleware' => ['islavel4','isactive']], function () {

            Route::get('first_reset_client_password', 'firmclient\FirmclientDashboardController@first_reset_password')->name('first_reset_client_password');

            Route::post('update_first_client_password', 'firmclient\FirmclientDashboardController@update_first_password')->name('update_first_client_password');

            Route::group(['middleware' => 'resetpassword'], function () {
                include_route_files(__DIR__.'/Firmclientfamily/');
            });
        }); 

    });
});



Route::middleware('auth')->get('logout', function() {
    Auth::logout();
    if(session()->has('info'))
    {
        return redirect(route('login'))->withInfo(session()->pull('info'));
    }
    return redirect(route('login'))->withInfo('You have successfully logged out!');
})->name('logout');

Auth::routes(['verify' => true]);

Route::name('js.')->group(function() {
    Route::get('dynamic.js', 'JsController@dynamic')->name('dynamic');
});

// Get authenticated user
Route::get('users/auth', function() {
    return response()->json(['user' => Auth::check() ? Auth::user() : false]);
});


Route::get('/messages', 'MessageController@index')->name('messages.index');
Route::get('/messages/NotificationCenter', 'MessageController@NotificationCenter')->name('messages.NotificationCenter');
Route::get('/messages/allread/{id}/{ids}', 'MessageController@allread')->name('messages.allread');
Route::get('/messages/chatUsers', 'MessageController@chatUsers')->name('messages.chatUsers');
Route::any('/messages/chatNote/{id}', 'MessageController@chatNote')->name('messages.chatNote');
Route::any('/messages/readnotification/{id}', 'MessageController@readnotification')->name('messages.readnotification');
Route::get('/messages/ReadNotify/{id}', 'MessageController@ReadNotify')->name('messages.ReadNotify');
Route::any('/messages/ChatInPopup/{id}', 'MessageController@ChatInPopup')->name('messages.ChatInPopup');
Route::any('/messages/view_unread_notification', 'MessageController@view_unread_notification')->name('messages.view_unread_notification');
Route::any('/messages/view_all_notification', 'MessageController@view_all_notification')->name('messages.view_all_notification');



Route::get('/messages/chat/{ids}', 'MessageController@chat')->name('messages.chat');
Route::get('/getCountries','HomeController@getCounties');
Route::get('/getStates/{id}','HomeController@getStates');
Route::get('/getCities/{id}','HomeController@getCities');
Route::get('/profile','HomeController@profile');
Route::post('/updateprofile','HomeController@updateprofile');
Route::get('/editpdf/{id}','HomeController@editpdf');
Route::get('/delete_card/{id}','HomeController@delete_card');
Route::get('/edit_questionnaire/{formtype}/{lang}/{id}','HomeController@edit_questionnaire');
Route::post('/update_questionnaire','HomeController@update_questionnaire');
Route::post('/add_questionnaire_fn','HomeController@add_questionnaire_fn');
Route::post('/send_invoice','HomeController@send_invoice');
Route::get('/viewinvoice/{id}','HomeController@viewinvoice');
Route::post('/pay_for_invoice','HomeController@pay_for_invoice');
Route::post('/sendinvoice/{id}','HomeController@sendinvoice');
Route::get('/printinvoice/{id}','HomeController@printinvoice');
Route::get('/delete_event/{id}','HomeController@delete_event');
Route::post('/UpdateFamily','HomeController@UpdateFamily');
Route::get('/NewQbookConnect','HomeController@NewQbookConnect');
Route::get('/FindShortCodeData/{id}/{shortcode}/{return}/{CID}', 'HomeController@FindShortCodeData')->name('pdfform.FindShortCodeData');
Route::post('/FindShortCodeDataSave', 'HomeController@FindShortCodeDataSave')->name('pdfform.FindShortCodeDataSave');
Route::any('/AjaxData/{action}', 'HomeController@AjaxData')->name('pdfform.AjaxData');
Route::any('/FileUpload/', 'HomeController@FileUpload')->name('pdfform.FileUpload');
Route::get('/logout_google','HomeController@logout_google');
Route::post('/setAdditionalDocument', 'HomeController@setAdditionalDocument');
Route::post('/addcasenotes','HomeController@addcasenotes');
Route::post('/sendtextmsg','HomeController@sendtextmsg');
Route::any('/search','HomeController@search');
// Outlook 

Route::get('/outlook/signin', 'outlook\AuthController@signin');
Route::get('/outlook/authorize', 'outlook\AuthController@gettoken');
Route::get('/outlook/mail', 'outlook\OutlookController@mail')->name('mail');
Route::get('/outlook/calendar', 'outlook\OutlookController@calendar')->name('calendar');
Route::get('/outlook/contacts', 'outlook\OutlookController@contacts')->name('contacts');



/*-------------Cronjob-------------*/

Route::get('/cron', 'CronjobController@index')->name('CronjobController.index');
Route::get('/cron/PdfMetaEnter', 'CronjobController@PdfMetaEnter')->name('CronjobController.PdfMetaEnter');
Route::get('/cron/TestPhpCode', 'CronjobController@TestPhpCode')->name('CronjobController.TestPhpCode');

Route::get('/cron/UserMonthlyPayment', 'CronjobController@UserMonthlyPayment')->name('CronjobController.UserMonthlyPayment');
Route::any('/cron/DirectUseHelper/{action}', 'CronjobController@DirectUseHelper')->name('CronjobController.DirectUseHelper');

LaravelProject/app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Mail\Mailable;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use App\Http\Controllers\Controller;
use App\Models\AdminTask;
use App\Models\Firm;
use App\Models\FirmCase;
use App\Models\Transaction;
use App\Models\DocumentRequest;
use Illuminate\Support\Facades\Auth;
use App\User;
use Mail;
use DB;

class DashboardController extends Controller
{
	public function __invoke(Request $request)
	{

		$currunt_user = Auth::User();
        $admintask = AdminTask::select('admintask.*','firms.firm_name')
        ->join('case', 'admintask.case_id', '=', 'case.id')
        ->join('firms', 'case.firm_id', '=', 'firms.id')
        ->join('users', 'admintask.firm_admin_id', '=', 'users.id')
        ->whereNotIn('admintask.task_type', ['Upload_Required_Document', 'Document_Action', 'Required_Document_Request', 'Additional_Service'])
        ->orderBy('created_at', 'DESC')
        ->limit(10)
        ->get();
        foreach ($admintask as $key => $value) {
            $admintask[$key]->allot_user_id = ($value->allot_user_id == 0) ? "NO" : "YES";
            $admintask[$key]->stat = ($value->status == 0) ? "Open" : "Complete";
            switch ($value->priority) {
                case 1:
                    $result = "Urgent";
                    break;
                case 2:
                    $result = "High";
                    break;
                case 3:
                    $result = "Medium";
                    break;
                case 4:
                    $result = "Low";
                    break;
                default:
                    $result = "Normal";
            }
            $ccid = $value->case_id;
            $admintask[$key]->is_edit = True; 
            if($admintask[$key]->stat == 'Complete') {
                $admintask[$key]->is_edit = false; 
            }
            if($value->task_type == 'provide_a_quote') {
                $doc = DocumentRequest::select('quote', 'case_id')->where('id', $ccid)->first();
                $admintask[$key]->is_edit = $doc['quote']; 
                $ccid = $doc['case_id'];
                $quote = $doc['quote'];
                if($quote == 3) {
                    $admintask[$key]->is_edit = false;
                }
            }
            $admintask[$key]->priority = $result;
            $case = FirmCase::select('case_type')->where('id', $ccid)->first();
            $admintask[$key]->case_type = $case['case_type'];
        }
        $count = [];
        $count['firm'] = Firm::where('status',1)->count();
        $count['cmsfirm'] = Firm::where('status',1)->where('account_type', 'CMS')->count();
        $count['vpfirm'] = Firm::where('status',1)->where('account_type', 'VP Services')->count();
        $count['vauser'] = User::where('role_id',2)->where('firm_id',0)->count();
        $count['revenue'] = Transaction::select('transactions.*')
                                ->where('transactions.paymenttype', '!=', 4)
                                ->join('users', 'users.id', '=', 'transactions.user_id')
                                ->join('firms', 'firms.id', '=', 'users.firm_id')
                                // ->where('firms.account_type', '=', 'VP Services')
                                ->sum('transactions.amount');
        $count['revenue'] = ($count['revenue'])/100;

        $count['cmsrevenue'] = Transaction::select('transactions.*')
                                ->where('transactions.paymenttype', '!=', 4)
                                ->join('users', 'users.id', '=', 'transactions.user_id')
                                ->join('firms', 'firms.id', '=', 'users.firm_id')
                                ->where('firms.account_type', '=', 'CMS')
                                ->sum('transactions.amount');
        $count['cmsrevenue'] = ($count['cmsrevenue'])/100;

        $count['vprevenue'] = Transaction::select('transactions.*')
                                ->where('transactions.paymenttype', '!=', 4)
                                ->join('users', 'users.id', '=', 'transactions.user_id')
                                ->join('firms', 'firms.id', '=', 'users.firm_id')
                                ->where('firms.account_type', '=', 'VP Services')
                                ->sum('transactions.amount');
        $count['vprevenue'] = ($count['vprevenue'])/100;

        $count['task'] = AdminTask::select('*')
                    ->whereNotIn('task_type', ['Upload_Required_Document', 'Document_Action', 'Required_Document_Request'])
                    ->where('status', 0)
                    ->count();
		return view('admin.dashboard.index', compact('admintask','count'));
	}

    public function adminbilling() {
        $firms = Firm::select('firms.*', 'users.id as user_id')
                ->join('users', 'users.email', '=', 'firms.email')
                ->get();
        $t = Transaction::select('amount')
            ->whereNotIn('type', ['Invoice'])
            ->sum('amount');
        $t = '$'.number_format(($t/100), 2);
        return view('admin.dashboard.billing', compact('firms', 't'));
    }

    public function getAdminBillingData(Request $request)
    { 
        $data = Auth::User();

        $q = "SELECT t.*, u1.name as username, f.firm_name, f.account_type FROM `transactions` as t
                LEFT JOIN `users` as u1 ON t.user_id = u1.id
                LEFT JOIN `firms` as f ON f.id = u1.firm_id WHERE 1 = 1";

        if(!empty($request->type)) {
            $q .= " AND t.type = '$request->type'";
        }
        if(!empty($request->pastdate)) {
            $d = $request->pastdate;
            $to = date('Y-m-d');
            $from = date('Y-m-d', strtotime("-$d day", strtotime($to)));
            $q .= " AND t.created_at BETWEEN '$from' AND '$to'";
        }
        if(!empty($request->from) && !empty($request->to)) {
            $f = $request->from;
            $t = $request->to;
            $f = explode('/', $request->from);
            $t = explode('/', $request->to);

            $from = $f[2] . '-' . $f[0] . '-' . $f[1];
            $to = $t[2] . '-' . $t[0] . '-' . $t[1];
            $q .= " AND t.created_at BETWEEN '$from' AND '$to'";
        }

        $Transaction = DB::select(DB::raw($q));

        foreach ($Transaction as $key => $value) {
            $Transaction[$key]->name = '';
            if(!empty($value->type) && $value->type != 'User') {
                // $case = FirmCase::select('case_type')->where('id', $value->related_id)->first();
                // $Transaction[$key]->name = $case->case_type;
            }
            else if(!empty($value->type) && $value->type == 'User') {
                $Transaction[$key]->name = 'Monthly user cost';
            }
            $Transaction[$key]->amount = '$'.number_format(($value->amount/100), 2);
        }
        return datatables()->of($Transaction)->toJson();
    }

    public function markasread()
    {
        Auth::User()->notifications->markAsRead();
        return redirect('admin/dashboard')->with('success','Notifications clear successfully ');
    }
}

LaravelProject/app/Http/Controllers/firmadmin/FirmProfileController.php
<?php

namespace App\Http\Controllers\firmadmin;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Storage;
use App\Http\Controllers\Controller;
use Carbon\Carbon;

use App\Models\Log;
use App\Models\FirmCase;
use App\Models\Lead;
use App\Models\Event;
use App\User;

use DB;
use App;

class FirmProfileController extends Controller
{
    public function __construct()
    {

    }
    

    public function index()
    {
        $user = Auth::User();
        $countries = DB::table("countries")->get();
        return view('firmadmin.profile.edit_profile',compact('user','countries'));
    }


    public function update_profile(Request $request)
    {
        
        $user_id = Auth::User()->id;
        $requestData = $request->all();
        $requestData['address'] = json_encode($request->birth_address1);

        $data = [
            'contact_number' => $requestData['contact_number'],
            'address' => $requestData['address']
        ];

        $check = User::where('id',$user_id)->update($data);

        if ($check) {
            return redirect('firm/profile')->with('success','Profile Updated successfully!');
        }else{
            return redirect('firm/profile')->with('error','Profile not updated, please try again');
        }

    }


    
}

LaravelProject/resources/views/firmadmin/dashboard/accountsetup.blade.php
@extends('layouts.admin-master')

@section('title')
Edit Firm
@endsection

@section('content')
<section class="section">
  <div class="section-header">
    <h1>Firm Account Set Up</h1>
    <div class="section-header-breadcrumb">
      
    </div>
  </div>
  <div class="section-body">
   
  		<div class="row">
  			<div class="col-md-12">
  				<div class="card">
        <form action="{{ url('firm/FirmAccountUpdate') }}" method="post" class="needs-validation" novalidate="">
          <div class="card-header">
            <h4>Firm Account Set Up</h4>
          </div>
          <div class="card-body">

          	<div class="form-group row mb-4">
          		<label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Firm Name
          		</label> 
          		<div class="col-sm-12 col-md-7">
          			<input type="text" placeholder="Firm Name" name="firm_name" class="form-control" required="" value="{{$firm->firm_name}}" /> 
          			<div class="invalid-feedback">Firm Name is required!</div>
          		</div>
          	</div> 
          	<div class="form-group row mb-4">
          		<label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Account Type
          		</label> 
          		<div class="col-sm-12 col-md-7">
                <input type="text" placeholder="Firm Name" name="account_type" class="form-control" required="" value="{{$firm->account_type}}" readonly="readonly" />
          			<div class="invalid-feedback">Please select Account Type!</div>
          		</div>
          	</div> 
          	<div class="form-group row mb-4">
          		<label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Firm Admin User's Email
          		</label> 
          		<div class="col-sm-12 col-md-7">
          			<input type="email" placeholder="Firm Admin User's Email." name="firm_admin_email" class="form-control" readonly="" value="{{$firm->email}}">  
          			<div class="invalid-feedback">Firm Admin User's Email is required!</div>
          		</div>
          	</div> 
          	
          	<div class="form-group row mb-4">
          		<label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Firm Admin User's Name
          		</label> 
          		<div class="col-sm-12 col-md-7">
          			<input type="text"  name="firm_admin_name" placeholder="Firm Admin User's Name" class="form-control" value="{{$firm->firm_admin_name}}" readonly="readonly"> 
          			<div class="invalid-feedback">Firm Admin User's Name is required!</div>
          		</div>
          	</div> 
          	<div class="form-group row mb-4">
          		<label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">
          		</label> 
          		<div class="col-sm-12 col-md-7">
          			@csrf
                <input type="hidden" name="firm_id" class="form-control" value="{{$firm->id}}" /> 
                <input type="hidden" name="user_id" class="form-control" value="{{$user->id}}" /> 
          			<button class="btn btn-primary" type="submit" name="create_firm_Account">
          				<span>Confirm</span>
          			</button>
          		</div>
          	</div>
          </div>
        </form>
      </div>
  			</div>
  		</div>
  </div>
</section>
@endsection

LaravelProject/resources/views/firmadmin/dashboard/conform_case.blade.php
@extends('firmlayouts.admin-master')

@section('title')
Case Conformation
@endsection

@section('content')
<section class="section">
  <div class="section-header">
    <h1>Case Conformation</h1>
    <div class="section-header-breadcrumb">
      <div class="breadcrumb-item">
        <a href="{{route('firm.admindashboard')}}">Dashboard</a>
      </div>
      <div class="breadcrumb-item">
        <a href="#">Conform Case</a>
      </div>
    </div>
  </div>
  <div class="section-body">
    
  		<div class="row">
  			<div class="col-md-12">
  				<div class="card">
            <div class="row">
              <div class="col-12 mb-4">
                <div class="hero text-white hero-bg-image hero-bg-parallax" style="background-image: url('{{ url('/') }}/assets/img/unsplash/andre-benz-1214056-unsplash.jpg');">
                  <div class="hero-inner">
                    <h2>Welcome, {{$user->name}}</h2>
                    <p class="lead">Do you want to reactivate Old Cases?</p>
                    <div class="mt-4">
                      <a href="{{ url('firm/caseIsConform')}}/{{$firm_id}}" class="btn btn-outline-white btn-lg btn-icon icon-left"><i class="far fa-user"></i>Yes</a>
                      
                      <a href="{{ url('/') }}" class="btn btn-outline-white btn-lg btn-icon icon-left"><i class="far fa-user"></i>Go to Dashboard</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
  			</div>
  		</div>
  </div>
</section>
@endsection

LaravelProject/resources/views/firmadmin/dashboard/createclient.blade.php
@extends('firmlayouts.admin-master')

@section('title')
Create Client
@endsection

@section('content')
<section class="section">
  <div class="section-header">
    <h1>Create Client</h1>
    <div class="section-header-breadcrumb">
      <div class="breadcrumb-item">
        <a href="{{route('firm.admindashboard')}}">Dashboard</a>
      </div>
      <div class="breadcrumb-item">
        <a href="#">Client Create</a>
      </div>
    </div>
  </div>
  <div class="section-body">
      <div class="row">
        <div class="col-md-12">
          <div class="card">
        <form action="{{ url('firm/users/create_user') }}" method="post" class="needs-validation" novalidate="">
          <div class="card-header">
            <h4>Create Client</h4>
          </div>
          <div class="card-body">
            <div class="form-group row mb-4">
              <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Client Name
              </label> 
              <div class="col-sm-12 col-md-7">
                <input type="text" placeholder="User Name" name="user_name" class="form-control" required=""> 
                <div class="invalid-feedback">Firm User Name is required!</div>
              </div>
            </div> 
            
            <div class="form-group row mb-4">
              <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Client Date of Birth
              </label> 
              <div class="col-sm-12 col-md-7">
                <input type="text" placeholder="User Name" name="user_name" class="form-control datepicker" required=""> 
                <div class="invalid-feedback">Firm User Name is required!</div>
              </div>
            </div> 

            <div class="form-group row mb-4">
              <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">User Email
              </label> 
              <div class="col-sm-12 col-md-7">
                <input type="email" placeholder="User Email." name="user_email" class="form-control" required=""> 
                <div class="invalid-feedback">Firm User Email is required!</div> 
              </div>
            </div> 

            <div class="form-group row mb-4">
              <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Account Type
              </label> 
              <div class="col-sm-12 col-md-7">
                <select class="form-control" required="" name="Role_type">
                  <option value="4">Firm Admin</option>
                  <option value="5">Firm User</option>
                  <option value="6">Firm Client</option>
                </select>
                <div class="invalid-feedback">Please select Role Type!</div> 
              </div>
            </div>

            <div class="form-group row mb-4">
              <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">User password
              </label> 
              <div class="col-sm-12 col-md-7">
                <input type="password" placeholder="User Password." name="user_password" class="form-control" required=""> 
                <div class="invalid-feedback">Firm User password is required!</div> 
              </div>
            </div> 
            
            <div class="form-group row mb-4">
              <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">
              </label> 
              <div class="col-sm-12 col-md-7">
                @csrf
                <button class="btn btn-primary" type="submit" name="create_firm_user">
                  <span>Create Firm user</span>
                </button>
              </div>
            </div>
          </div>
        </form>
      </div>
        </div>
      </div>
      <!-- <adduser-component></adduser-component> -->
  </div>
</section>
@endsection

LaravelProject/resources/views/firmadmin/dashboard/payment_succcess.blade.php
@extends('layouts.admin-master')

@section('title')
Edit Firm
@endsection

@section('content')
<section class="section">
  <div class="section-header">
    <h1>Firm Account</h1>
    <div class="section-header-breadcrumb">
      <div class="breadcrumb-item">
        <a href="{{route('firm.admindashboard')}}">Dashboard</a>
      </div>
      <div class="breadcrumb-item">
        <a href="#">Payment success</a>
      </div>
    </div>
  </div>
  <div class="section-body">
   
  		<div class="row">
  			<div class="col-md-12">
  				<div class="card">
            <div class="row">
              <div class="col-12 mb-4">
                <div class="hero text-white hero-bg-image hero-bg-parallax" style="background-image: url('{{ url('/') }}/assets/img/unsplash/andre-benz-1214056-unsplash.jpg');">
                  <div class="hero-inner">
                    <h2>Welcome, TILA</h2>
                    <p class="lead">Did you want to add first client?</p>
                    <div class="mt-4">
                      <a href="{{ url('firm/client/create') }}" class="btn btn-outline-white btn-lg btn-icon icon-left"><i class="far fa-user"></i>Yes</a>
                      
                      <a href="{{ url('firm/schedule_training') }}" class="btn btn-outline-white btn-lg btn-icon icon-left"><i class="far fa-user"></i>No</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
  			</div>
  		</div>
  </div>
</section>
@endsection